@extends('layouts.app')
@section('content')
<div><a href="{{ route('client.services.index') }}" class="text-sm text-indigo-700">← Kembali ke layanan</a><h1 class="mt-3 text-3xl font-semibold">{{ $service->name }}</h1><p class="mt-1 text-slate-600">Isi data dasar. Dokumen dapat diunggah setelah draft dibuat.</p></div>
<form method="post" action="{{ route('client.applications.store') }}" class="mt-8 space-y-6">@csrf<input type="hidden" name="service_public_id" value="{{ $service->public_id }}"><input type="hidden" name="kind" value="{{ $service->code }}">
    @if($service->code === 'NPWP_PERSONAL')
        <section class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="font-semibold">Data perseorangan</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm font-medium md:col-span-2">Nama lengkap<input name="name" value="{{ old('name', auth()->user()->name) }}" required class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Email<input name="email" type="email" value="{{ old('email', auth()->user()->email) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Jenis kelamin<input name="gender" value="{{ old('gender') }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Status pernikahan<input name="marital_status" value="{{ old('marital_status') }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Status dalam keluarga<input name="family_status" value="{{ old('family_status') }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium md:col-span-2">Keperluan NPWP<input name="purpose" value="{{ old('purpose') }}" class="mt-1 w-full rounded-lg border-slate-300"></label></div></section>
    @else
        <section class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="font-semibold">Data badan usaha</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm font-medium md:col-span-2">Nama badan usaha<input name="business_name" value="{{ old('business_name') }}" required class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Jenis badan usaha<select id="business-type" name="business_type" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Pilih jenis badan usaha</option>@foreach(\App\Enums\BusinessType::cases() as $type)<option value="{{ $type->value }}" @selected(old('business_type', $selectedBusinessType) === $type->value)>{{ $type->label() }}</option>@endforeach</select></label><label id="business-type-other-field" class="text-sm font-medium" @if(old('business_type', $selectedBusinessType) !== 'OTHER') hidden @endif>Jenis badan usaha lainnya<input name="business_type_other" value="{{ old('business_type_other') }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Keperluan NPWP<input name="purpose" value="{{ old('purpose') }}" class="mt-1 w-full rounded-lg border-slate-300"></label></div><div class="mt-6 border-t pt-5"><h3 class="font-medium">Penanggung jawab utama</h3><div class="mt-3 grid gap-4 md:grid-cols-3"><label class="text-sm font-medium">Nama<input name="representative[name]" value="{{ old('representative.name') }}" required class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Hubungan<select name="representative[relationship]" required class="mt-1 w-full rounded-lg border-slate-300">@foreach(['OWNER','DIRECTOR','MANAGEMENT','EMPLOYEE','AUTHORIZED_REPRESENTATIVE','OTHER'] as $relationship)<option value="{{ $relationship }}">{{ str_replace('_', ' ', $relationship) }}</option>@endforeach</select></label><label class="text-sm font-medium">Email<input name="representative[email]" type="email" value="{{ old('representative.email') }}" class="mt-1 w-full rounded-lg border-slate-300"></label></div></div></section>
    @endif
    @if($service->code === 'NPWP_BUSINESS')<section class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="font-semibold">Representative tambahan (opsional)</h2><div class="mt-4 grid gap-4 md:grid-cols-3"><label class="text-sm font-medium">Nama<input name="additional_representative[name]" value="{{ old('additional_representative.name') }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Hubungan<select name="additional_representative[relationship]" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Pilih bila ada</option>@foreach(['OWNER','DIRECTOR','MANAGEMENT','EMPLOYEE','AUTHORIZED_REPRESENTATIVE','OTHER'] as $relationship)<option value="{{ $relationship }}">{{ str_replace('_', ' ', $relationship) }}</option>@endforeach</select></label><label class="text-sm font-medium">Email<input name="additional_representative[email]" type="email" value="{{ old('additional_representative.email') }}" class="mt-1 w-full rounded-lg border-slate-300"></label></div></section>@endif
    <label class="flex items-start gap-3 rounded-xl bg-white p-5 text-sm ring-1 ring-slate-200"><input type="checkbox" name="consent" value="1" required class="mt-1 rounded border-slate-300"><span>Saya menyetujui pemrosesan data untuk layanan ini sesuai informasi aplikasi. Saya memahami Bantu Daftarin bukan sistem resmi pemerintah.</span></label>
    <button class="rounded-lg bg-indigo-600 px-5 py-2 font-medium text-white">Simpan draft</button>
</form>
@if($service->code === 'NPWP_BUSINESS')
<script>
(() => {
    const type = document.getElementById('business-type');
    const other = document.getElementById('business-type-other-field');
    if (!type || !other) return;
    const update = () => { other.hidden = type.value !== 'OTHER'; };
    type.addEventListener('change', update);
    update();
})();
</script>
@endif
@endsection
